--INSERT INTO [dbo].[Group] ([Description], [GroupCode], [IsActive], [Name], [Remark], [Sequence],[Type]) VALUES (NULL, 'softdrinks', 0, 'Soft Drinks', NULL, 0, NULL)
--INSERT INTO [dbo].[Group] ([Description], [GroupCode], [IsActive], [Name], [Remark], [Sequence],[Type]) VALUES (NULL, 'c', 0, 'Starter', NULL, 0, NULL)
--INSERT INTO [dbo].[Elements] ([Description],[ElementCode],[GroupCode],[IsActive],[Remark],[Type],[UOM]) VALUES('Mirinda','SD01','softdrinks',0,NULL,NULL,NUll)
--INSERT INTO [dbo].[Elements] ([Description],[ElementCode],[GroupCode],[IsActive],[Remark],[Type],[UOM]) VALUES('Starter 2','ST02','c',0,NULL,NULL,NUll)
--INSERT INTO [dbo].[Persons] ([Active],[DateOFBirth],[FirstName],[Gender],[Group],[LastName],[MiddleName],[Nationality],[PersonCode]) VALUES(0,'1900/01/01','Habte','Male',NULL,'Adugna',null,null,'Pe02')
--INSERT INTO [dbo].[Persons] ([Active],[DateOFBirth],[FirstName],[Gender],[Group],[LastName],[MiddleName],[Nationality],[PersonCode]) VALUES(0,'1900/01/01','Maya','Female',NULL,'Yobeltal',null,null,'Pe03')
--INSERT INTO [dbo].[Users] ([Code], [username], [password], [PersonCode], [IsActive], [loggedInStatus]) VALUES ('Us02','habte', 'Ha123', 'Pe02', 0, 0)
--INSERT INTO [dbo].[Users] ([Code], [username], [password], [PersonCode], [IsActive], [loggedInStatus]) VALUES ('Us03','maya', 'MA123', 'Pe03', 0, 0)
INSERT INTO [dbo].[Prices] ([Code],[Currency],[Decription],[ElementCode],[IsDefault],[PriceValue],[priority],[Remark]) VALUES('pr02',null,null,'ST02',1,14.0,0,null)
INSERT INTO [dbo].[Prices] ([Code],[Currency],[Decription],[ElementCode],[IsDefault],[PriceValue],[priority],[Remark]) VALUES('pr07',null,null,'SD01',1,25.0,0,null)
